<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta name="language" content="zh-CN"/>
    <meta name="robots" content="all">
    <meta name="author" content="lygus0@gmail.com">
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <title>Error</title>
    <style type="text/css">
        html, body{ height:100%; }
        body{
            padding-top:40px;
            padding-bottom:40px;
            background:none #f5f5f5;
        }
		h4{
			color: inherit;
			font-family: inherit;
			font-weight: bold;
			line-height: 20px;
			margin: 10px 0;
			text-rendering: optimizelegibility;}
		.alert-error{
			background-color: #F2DEDE;
			border-color: #EED3D7;
			color: #B94A48;
			text-align:center;
			font-family: "Helvetica Neue",Helvetica,Arial,sans-serif;
			font-size: 14px;
			line-height: 20px
			border-radius: 4px;
			margin-bottom: 20px;
			padding: 8px 35px 8px 14px;
			text-shadow: 0 1px 0 rgba(255, 255, 255, 0.5);
			}
	.text-center{color: #333333;
		font-family: "Helvetica Neue",Helvetica,Arial,sans-serif;
		font-size: 14px;
		line-height: 20px;
		text-align:center;
		}	
    .form-signin{
            max-width:500px;
            padding:19px 29px 29px;
            margin:0 auto 20px;
            background-color:#fff;
            border:1px solid #e5e5e5;
            -webkit-border-radius:5px;
            -moz-border-radius:5px;
            border-radius:5px;
            -webkit-box-shadow:0 1px 2px rgba(0, 0, 0, .05);
            -moz-box-shadow:0 1px 2px rgba(0, 0, 0, .05);
            box-shadow:0 1px 2px rgba(0, 0, 0, .05);}
    </style>
</head>
<body>

<div class="container">
    <div class="form-signin">
        <div class="row">
            <div><img src="/static/img/logo.png"/></div>
        </div>

        <h4>错误 <?php echo $this->error;?></h4>
		
		<p class="alert-error"><?php echo $this->message;?></p>
        <p class="text-center"><a href="/">返回首页</a>&nbsp;&nbsp;<a href="javascript:history.go(-1);">返回上一页</a></p>
    </div>
</div>

</body>

</html>