
			<div class="block">
				<div class="l-des-t">我发布的书  · · · · · ·(<a href="#"><?php echo $this->fbc;?>本发布</a>)</div>
					<div class="l-more t20">
						<ul>
						<?php foreach($this->fb as $f){?>
							<li>
								<a href="#"><img src="<?php echo $f['cover'];?>"/></a>
								<p><?php echo $f['subject'];?></p>
							</li>
						<?php }?>	
						</ul>
					</div>
				</div>	
				
				<div class="block t20">
				<div class="l-des-t">我关注的  · · · · · ·(<a href="#">4关注</a>)</div>
					<div class="l-more t20">
						<ul>
							<li>
								<a href="#"><img src="/static/img/t1.jpg"/></a>
							</li>
							<li>
								<a href="#"><img src="/static/img/t2.jpg"/></a>
							</li>
							<li>
								<a href="#"><img src="/static/img/t1.jpg"/></a>
							</li>
							<li>
								<a href="#"><img src="/static/img/t2.jpg"/></a>
							</li>
							<li>
								<a href="#"><img src="/static/img/t1.jpg"/></a>
							</li>
							<li>
								<a href="#"><img src="/static/img/t2.jpg"/></a>
							</li>
							<li>
								<a href="#"><img src="/static/img/t1.jpg"/></a>
							</li>
							<li>
								<a href="#"><img src="/static/img/t2.jpg"/></a>
							</li>
							
						</ul>
					</div>
				</div>