<div class="yo_t">什么是kindleyo?</div>

<div style="padding:2px;margin-top:10px;">
	<p>
	<span style="color:#666666;font-family:sans-serif;font-size:13px;line-height:normal;"><span style="color:#666666;">&nbsp; &nbsp; </span><span style="color:#666666;">信息就是力量。但就像所有力量一样，有些人只想占为己有。世界上所有的科学和文化遗产，已在书籍和期刊上发布了数个世纪， 正渐渐地被少数私有的公司数字化并上锁。想要阅读那些有着最著名研究成果的论文？你必须支付给如 Reed Elsevier 这样的出版商大把钱。&nbsp;</span></span>
</p>
<span style="color:#666666;font-family:sans-serif;font-size:13px;line-height:normal;">&nbsp;&nbsp;&nbsp;&nbsp;只要全世界有足够多的我们，那就不仅是传达了一个反对知识私有化的强有力信号，我们还将让它成为过去。你愿意和我们一起吗？</span>
<p style="color:#666666;font-family:sans-serif;font-size:13px;">
	<span style="color:#666666;">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</span><span style="color:#666666;">亚伦·斯沃茨 (Aaron Swartz)</span>
</p>
<p style="color:#666666;font-family:sans-serif;font-size:13px;">
	<span style="color:#666666;">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</span><span style="color:#666666;">2008 年 7 月，意大利 Eremo</span>
</p>
<p style="color:#666666;font-family:sans-serif;font-size:13px;">
	<span style="color:#666666;">&nbsp;&nbsp;&nbsp;&nbsp;<br />
</span>
</p>
<p style="color:#666666;font-family:sans-serif;font-size:13px;">
	<span style="color:#666666;">&nbsp;&nbsp;&nbsp;&nbsp;2013年1月11日,Aaron Swartz这位天才自杀了,Aaron觉得那些对人类有价值的科学和文化遗产属于全人类,在他的青少年时期，他就在不懈地和一切限制信息自由交换和自由共享的做法做斗争。这是他认为的互联网精神，他同时也觉得这和美国民主自由的宪法的精神是一致的.18岁时Aaron创建了Internet Open Library, 他希望把那些没有Copyright的书籍和学术期刊放在网上让全世界的人免费查阅.<br />
</span>
</p>
<p style="color:#666666;font-family:sans-serif;font-size:13px;">
	<span style="color:#666666;">&nbsp; &nbsp;那年Aaron才24岁。2011年7月11日，美国政府检查官通过钓鱼执法,以通信欺诈、计算机欺诈、非法获得信息，以及破坏被保护的罪名电脑来起诉他。可能会受到35年以上的牢狱之灾,当时有2条路可供Aaron选择:1认罪，承认犯下重罪，35年的判决会变成3个月入狱+1年的居家监禁（不得使用电脑），2）不认罪，那就有可能接受35监禁年的最坏结果。Aaron选择了后者.<br />
</span>
</p>
<p style="color:#666666;font-family:sans-serif;font-size:13px;">
	<span style="color:#666666;">&nbsp;&nbsp;&nbsp;&nbsp;而在次年2012年9月，政府对Aaron进行了更为严厉的起诉，新加入了另外9条起诉，如果成立，Aaron最多获刑50年外加100万美金的罚款。同样，检察官给出了优惠条件，只要Aaron认罪，那就只起诉他6个月的监禁。Aaron再次拒绝。<br />
</span>
</p>
<p style="color:#666666;font-family:sans-serif;font-size:13px;">
	<span style="color:#666666;">&nbsp;&nbsp;&nbsp;&nbsp;美国当地时间2013年1月11自杀身亡，年仅26岁.</span><br />
	<span style="color:#666666;">&nbsp; &nbsp; Aaron对于知识传播开放自由的精神,也正是kindleyo创立的初衷.</span>
</p>

<p style="color:#666666;font-family:sans-serif;font-size:13px;">
	<span style="color:#666666;">&nbsp;&nbsp;&nbsp;<span style="color:#666666;">&nbsp;</span><span style="color:#666666;font-family:'Microsoft YaHei', Arial, Helvetica, sans-serif;font-size:12px;line-height:24px;background-color:#FFFFFF;">我们被教导要记住思想，而不是人，因为人可能失败，他可能会被捕，他会被杀死，被遗忘，但400年后，思想仍可改变世界。我亲眼目睹了思想的力量，我见过人们以它为名杀戮，或是为了维护它献出</span><span style="font-size:12px;color:#666666;">生命</span><span style="color:#666666;font-family:'Microsoft YaHei', Arial, Helvetica, sans-serif;font-size:12px;line-height:24px;background-color:#FFFFFF;">，但你不能亲吻思想，也不能触摸它或抱着它，思想不会流血，不会感到痛苦，它们没有爱。</span><span style="font-size:12px;color:#666666;"></span><br />
</span>
</p>

</div>
