<div class="yo_t">帮助推广</div>

<div style="padding:2px;margin-top:10px;color:#666;">
	<a href="http://www.hao123.com/"><img src="http://www.hao123.com/static/images/public/logo.jpg" style="width:188px;height:61px;" alt=“hao123上网导航” /></a>
	
	<a href="http://hao.360.cn/" target="_blank"><img src="http://h1.qhimg.com/images/logo_def.png" style="width:188px;height:61px;"/></a>
	
	<a href="http://123.sogou.com/" target="_blank"><img src="http://d.123.sogou.com/imgn/v32/logo_1112292.png" style="width:188px;height:61px;"/></a>
	
	<a target="_blank" href="http://www.3456.cc"><img alt="3456网址导航" src="http://www.3456.cc/images/logo.gif"   style="width:188px;height:61px;" border="0"></a>

	
</div>
