		
		<div class="content t50">
			<div class="reg-t">用户注册</div>
			<div class="article">
				<div class="block">
					<form id="rform" method="post" action="">
						<div class="reg-line">
							<div class="reg-name">邮箱</div>
							<div class="reg-ipt"><input type="text" id="mail" name="mail"/></div>
							<div class="reg-msg" id="m-msg"></div>
						</div>
						<div class="reg-line">
							<div class="reg-name">昵称</div>
							<div class="reg-ipt"><input type="text" id="nick" name="nick"/></div>
							<div class="reg-msg" id="n-msg"></div>
						</div>
						<div class="reg-line">
							<div class="reg-name">密码</div>
							<div class="reg-ipt"><input type="password" id="pwd" name="pwd"/></div>
							<div class="reg-msg" id="p-msg"></div>
						</div>
						<div class="reg-line">
							<div class="reg-name">验证码</div>
							<div class="reg-ipt"><input type="text" id="verify" name="verify" style="width:80px;"/><img src="/user/captcha" onclick="this.src='/user/captcha?='+Math.random()"/></div>
							<div class="reg-msg" id="v-msg"></div>
						</div>
						<div class="reg-line"></div>
						<div class="reg-line">
							<div class="reg-name"></div>
							<div class="reg-ipt"><a id="u-reg" href="#">注&nbsp;&nbsp;册</a></div>
						</div>
					</form>
				</div>		
			</div><!--article-->

			<div class="aside">
				<div class="reg-line reg-r">
				>已经拥有账号?
				<a href="/user/login">直接登录</a>
				</div>
			</div>
			
			<div class="content">
				<div class="footer">
					<div class="copyright">© 2014 kindleyo.com, all rights reserved</div>
					<div class="listen"><a href="#">关于看雨</a>·<a href="#">相关声明</a>·<a href="#">广告投放</a>·<a href="#">帮助推广</a></div>
				</div>
			</div>
		</div>
		<script>
			$('#u-reg').click(function(){
				var m  = $('#mail').val();			
				var mp = /^([a-zA-Z0-9_-])+@([a-zA-Z0-9_-])+.com+/;
				var n  = $('#nick').val();
				var np =  /^[0-9A-Za-z_]{4,16}$/;
				var p  = $('#pwd').val();
				var pp = /^[0-9A-Za-z_]{6,16}$/;
				
				if(!mp.test(m)){
					$('#m-msg').html('邮箱为空或格式错误');
					return;
				}else{$('#m-msg').html('');}
				if(!np.test(n)){
					$('#n-msg').html('昵称长度4-16');
					return;
				}else{$('#n-msg').html('');}
				if(!pp.test(p)){
					$('#p-msg').html('密码长度6-16');
					return;
				}else{$('#p-msg').html('');}
				if($('#verify').val() == ''){
					$('#v-msg').html('验证码为空');
					return;
				}else{$('#v-msg').html('');}
				
				$.ajax({
					cache: false,
					type: "POST",
					url:"/user/reg",
					data:$('#rform').serialize(),
					async: false,
					success: function(msg) {
						switch(parseInt(msg)){
							case 1: $('#m-msg').html('邮箱为空或格式错误');break;
							case 2: $('#m-msg').html('邮箱已存在');break;
							case 3: $('#n-msg').html('昵称错误');break;
							case 4: $('#p-msg').html('密码错误');break;
							case 5: $('#v-msg').html('验证码错误');break;
							case 6: window.location.href='/';break;
						}
					}
				});
			});
		</script>