		
		<div class="top">
			<div class="content">
				<div class="logo"></div>
				<div class="c-nav">
				<div class="up-h">图书投稿系统</div>
				</div>
			</div>
		</div>
		
		<div class="content">	
			
			<?php echo $this->content;?>
			
		</div>
			<div class="content">
				<div class="footer">
					<div class="copyright">© 2014 kindleyo.com, internet open library</div>
					<div class="listen"><a href="/yo/about">关于看雨</a>·<a href="/yo/disclaimer">相关声明</a>·<a href="/yo/advert">广告投放</a>·<a href="/yo/disseminate">帮助推广</a></div>
				</div>
				<div class="union">
					<a href="https://www.upyun.com" target="_blank"><img src='http://upfiles.b0.upaiyun.com/logo/90x45.png' /></a>
					<a href="https://portal.qiniu.com/signup?code=3lho3jzftg7de" target="_blank"><img src="/static/img/qiniu_logo.png"></a>
					<a href="http://lygus0.jd-app.com" target="_blank"><img src="/static/img/blog.png"></a>
				</div>
			</div>